## team5-config/argocd/projects/monitoring-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring stack for local VirtualBox k8s cluster

  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://github.com/imzinfsec/team5-config.git # 💡 대장님 개인 깃허브 주소로 변경

  destinations:
    # 💡 AWS 주소 4개를 싹 청소하고 로컬 클러스터 통로 하나만 시원하게 뚫어줍니다!
    - server: "https://kubernetes.default.svc"
      namespace: monitoring
    - server: "https://kubernetes.default.svc"
      namespace: kube-system

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"