apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petcarelog-prod
  namespace: argocd
spec:
  description: PetCareLog Prod Environment Project

  sourceRepos:
    - https://github.com/imzinfsec/team5-config.git

  destinations:
    - server: "https://2467051C6CE1E002CF1634B37DFC3D77.gr7.ap-northeast-2.eks.amazonaws.com"
      namespace: petcarelog-prod

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"