## team5-config/argocd/projects/petcarelog-dev-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petcarelog-dev
  namespace: argocd
spec:
  description: PetCareLog Dev Environment Project

  sourceRepos:
    - https://github.com/imzinfsec/team5-config.git

  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: petcarelog-dev

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"