## petcarelog-dev-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petcarelog-dev
  namespace: argocd
spec:
  description: PetCareLog Dev Environment Project

  sourceRepos:
    - https://github.com/imzinfsec/team5-config.git

  destinations:
    # 💡 AWS EKS 주소를 지우고, 로컬 자기 자신을 가리키는 내부 주소로 변경합니다!
    - server: "https://kubernetes.default.svc"
      namespace: petcarelog-dev

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"