apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcarelog
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: petcarelog
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team5-petcarelog-prod:9caf6936e6f8a03fbce2c93bfa54c47a28368f10