## apps/petcarelog/base/dev/patch-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: petcarelog
# spec:
#   replicas: 1
#   template:
#     spec:
#       containers:
#         - name: petcarelog
#           image: imzinfsec/team5-petcarelog-dev:4062d625d2ec3535e77b05eeebf28bb966949858

apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcarelog
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: petcarelog
          # 💡 가장 최신 이미지를 뜻하는 latest 태그를 바라보게 설정합니다.
          image: imzinfsec/team5-petcarelog-dev:4062d625d2ec3535e77b05eeebf28bb966949858

# Bash
# # 1. 도커 허브 로그인 (아이디와 비밀번호 입력창이 뜹니다)
# docker login -u imzinfsec

# # 2. 로컬에서 자바 소스 코드를 기반으로 도커 이미지 직접 빌드
# docker build -t imzinfsec/team5-petcarelog-dev:latest .

# # 3. 빌드된 이미지를 방금 만든 도커 허브 저장소로 업로드!
# docker push imzinfsec/team5-petcarelog-dev:latest