grafana:
  service:
    type: ClusterIP

  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 700m
        memory: 2Gi

alertmanager:
  enabled: true

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true