## team5-config/argocd/applicationsets/monitoring-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # 🟢 개발계 환경 카드 설정
          - env: dev
            cluster: "https://kubernetes.default.svc"
            namespace: monitoring
            valuesFile: values-dev.yaml

          # 🔵 운영계 환경 카드 설정 (AWS 주소를 로컬 주소로 변경!)
          - env: prod
            cluster: "https://kubernetes.default.svc"
            namespace: monitoring
            valuesFile: values-prod.yaml

  template:
    metadata:
      name: 'monitoring-{{env}}'
    spec:
      project: default

      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 58.7.2
          helm:
            valueFiles:
              - $values/monitoring/kube-prometheus-stack/{{valuesFile}}

        # 💡 팀 깃허브 주소를 대장님의 개인 깃허브 주소로 변경
        - repoURL: https://github.com/imzinfsec/team5-config.git
          targetRevision: main
          ref: values

      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true