## team5-config/argocd/applicationsets/monitoring-crds-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-crds-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: "https://kubernetes.default.svc"
          - env: prod
            cluster: "https://kubernetes.default.svc"

  template:
    metadata:
      name: 'monitoring-crds-{{env}}'
    spec:
      project: default

      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-operator-crds
        targetRevision: 17.0.2

      destination:
        server: '{{cluster}}'
        namespace: monitoring

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true