apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: petcarelog-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
#            cluster: "https://A03190C7D9EE01AAEB6B4267879D819A.gr7.ap-northeast-2.eks.amazonaws.com"
            cluster: "https://kubernetes.default.svc"
            namespace: petcarelog-dev

          - env: prod
#            cluster: "https://341C11627D397F927673C22681F5E6F6.gr7.ap-northeast-2.eks.amazonaws.com" 
            cluster: "https://kubernetes.default.svc"
            namespace: petcarelog-prod

  template:
    metadata:
      name: 'petcarelog-{{env}}'
    spec:
      project: 'petcarelog-{{env}}'

      source:
        repoURL: 'https://github.com/imzinfsec/team5-config.git'
        targetRevision: HEAD
        path: 'apps/petcarelog/overlays/{{env}}'

      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true